# Generated by Django 3.2 on 2022-11-16 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=11, verbose_name='Телефон')),
                ('office', models.CharField(blank=True, max_length=200, verbose_name='Кабинет')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('department', models.CharField(max_length=200, verbose_name='Отдел')),
                ('type', models.CharField(choices=[('E', 'Работник'), ('C', 'Клиент')], default='E', max_length=10, verbose_name='Тип аккаунта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
